mkdir:
	mkdir -p ./out

conv57_test_hard: mkdir
	gcc conv57src/conv57_test_hard.c -o ./out/conv57_test_hard
	./out/conv57_test_hard

conv57_test_soft: mkdir
	gcc conv57src/conv57_test_soft.c -o ./out/conv57_test_soft
	./out/conv57_test_soft
